export const ADD_POST = "ADD_POST"
export const REMOVE_POST = "REMOVE_POST"
export const ADD_COMMENT = "ADD_COMMENT"
export const REMOVE_COMMENT = "REMOVE_COMMENT"
export const EDIT_POST = "EDIT_POST"
export const LOAD_POSTS = "LOAD_POSTS"
export const LOAD_FULL_POST = "LOAD_FULL_POST"